version: "3"
services:
  reverseproxy:
      image: ulhaspai/reverseproxy
      ports:
          - 6003:6003
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: ulhaspai/udacity-c3-restapi-user
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      UDAGRAM_USERNAME: $UDAGRAM_USERNAME
      UDAGRAM_PASSWORD: $UDAGRAM_PASSWORD
      UDAGRAM_DATABASE: $UDAGRAM_DATABASE
      UDAGRAM_DATABASE_HOST: $UDAGRAM_DATABASE_HOST
      AWS_PROFILE: $AWS_PROFILE
      UDAGRAM_S3_BUCKET: $UDAGRAM_S3_BUCKET
      JWT_SECRET: $JWT_SECRET
      UDAGRAM_URL: "http://localhost:8100"
      PORT: $PORT
  backend-feed:
    image: ulhaspai/udacity-c3-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      UDAGRAM_USERNAME: $UDAGRAM_USERNAME
      UDAGRAM_PASSWORD: $UDAGRAM_PASSWORD
      UDAGRAM_DATABASE: $UDAGRAM_DATABASE
      UDAGRAM_DATABASE_HOST: $UDAGRAM_DATABASE_HOST
      AWS_PROFILE: $AWS_PROFILE
      UDAGRAM_S3_BUCKET: $UDAGRAM_S3_BUCKET
      JWT_SECRET: $JWT_SECRET
      UDAGRAM_URL: "http://localhost:8100"
      PORT: $PORT
  frontend:
    image: ulhaspai/udacity-c3-frontend
    ports:
      - "8100:80"
