apiVersion: apps/v1

kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  selector:
    matchLabels:
      service: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - image: ulhaspai/udacity-c3-restapi-user
        name: backend-user
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
          - name: UDAGRAM_URL
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: UDAGRAM_URL
          - name: UDAGRAM_S3_BUCKET
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: UDAGRAM_S3_BUCKET
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: AWS_PROFILE
          #        - name: AWS_REGION
          #          valueFrom:
          #            configMapKeyRef:
          #              name: env-config
          #              key: AWS_REGION
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: JWT_SECRET
          - name: UDAGRAM_DATABASE
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: UDAGRAM_DATABASE
          - name: UDAGRAM_DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: UDAGRAM_DATABASE_HOST
          - name: UDAGRAM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: UDAGRAM_PASSWORD
          - name: UDAGRAM_USERNAME
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: UDAGRAM_USERNAME
      restartPolicy: Always


