apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  selector:
    matchLabels:
      app: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - image: ulhaspai/reverseproxy
        name: reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 6003
      restartPolicy: Always


